from enum import Enum


class DeviceEventType(str, Enum):
    DEVICE_CREATED = "DEVICE_CREATED"
    DEVICE_UPDATED = "DEVICE_UPDATED"
    DEVICE_DELETED = "DEVICE_DELETED"
    POWER_READING = "POWER_READING"
    DEVICE_COMMAND = "DEVICE_COMMAND"
    UPDATE_REQUEST = "UPDATE_REQUEST"

    DEVICE_ON = "DEVICE_ON"
    DEVICE_OFF = "DEVICE_OFF"
    GPIO_CHANGE = "GPIO_CHANGE"


class DeviceTriggerMode(str, Enum):
    
    AUTO_TRIGGER = "AUTO_TRIGGER"
    SCHEDULE_TRIGGER = "SCHEDULE_TRIGGER"
    MANUAL_TRIGGER = "MANUAL_TRIGGER"
    ERROR = "ERROR"


class EventType(str, Enum):
    DEVICE_CREATED = "DEVICE_CREATED"
    DEVICE_UPDATED = "DEVICE_UPDATED"
    DEVICE_DELETED = "DEVICE_DELETED"
    POWER_READING = "POWER_READING"
    DEVICE_COMMAND = "DEVICE_COMMAND"
    UPDATE_REQUEST = "UPDATE_REQUEST"
