"""auto migration 2025-12-26T12:26:18.921251+00:00

Revision ID: 4c0081a4b9e2
Revises: f920f5ff118b
Create Date: 2025-12-26 13:26:19.138979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c0081a4b9e2'
down_revision: Union[str, Sequence[str], None] = 'f920f5ff118b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microcontrollers', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microcontrollers', 'config')
    # ### end Alembic commands ###
