"""auto migration 2026-01-30T18:22:29.586841+00:00

Revision ID: 633c213f079c
Revises: e599cbe80578
Create Date: 2026-01-30 19:22:29.809543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633c213f079c'
down_revision: Union[str, Sequence[str], None] = 'e599cbe80578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_microcontroller_id'), table_name='providers')
    op.drop_constraint(op.f('providers_microcontroller_id_fkey'), 'providers', type_='foreignkey')
    op.drop_column('providers', 'microcontroller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('microcontroller_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('providers_microcontroller_id_fkey'), 'providers', 'microcontrollers', ['microcontroller_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_providers_microcontroller_id'), 'providers', ['microcontroller_id'], unique=False)
    # ### end Alembic commands ###
