"""auto migration 2026-02-20T18:52:56.480763+00:00

Revision ID: 65b41d7438f7
Revises: 9e75726689cb
Create Date: 2026-02-20 19:52:56.679422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b41d7438f7'
down_revision: Union[str, Sequence[str], None] = '9e75726689cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('rated_power', sa.Numeric(precision=12, scale=4), nullable=True))
    op.drop_column('devices', 'rated_power_w')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('rated_power_w', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.drop_column('devices', 'rated_power')
    # ### end Alembic commands ###
