"""auto migration 2025-12-17T16:50:14+00:00

Revision ID: 8f4021a81b6d
Revises: 
Create Date: 2025-12-17 17:50:14.655581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4021a81b6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'NEW', 'CLIENT', 'CLIENT_PRO', 'DEMO', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('station_code', sa.String(length=255), nullable=False),
    sa.Column('station_addr', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installations_id'), 'installations', ['id'], unique=False)
    op.create_index(op.f('ix_installations_station_code'), 'installations', ['station_code'], unique=True)
    op.create_index(op.f('ix_installations_user_id'), 'installations', ['user_id'], unique=False)
    op.create_table('microcontrollers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('RASPBERRY_PI_ZERO', name='microcontroller_type_enum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('software_version', sa.String(), nullable=True),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microcontrollers_installation_id'), 'microcontrollers', ['installation_id'], unique=False)
    op.create_index(op.f('ix_microcontrollers_uuid'), 'microcontrollers', ['uuid'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('microcontroller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.Enum('API', 'SENSOR', 'VIRTUAL', name='provider_type_enum'), nullable=False),
    sa.Column('kind', sa.Enum('PV_INVERTER', 'TEMPERATURE', 'HUMIDITY', 'LIGHT', 'POWER', name='provider_kind_enum'), nullable=False),
    sa.Column('vendor', sa.Enum('HUAWEI', 'GOODWE', 'SIEMENS', 'DHT22', 'BME280', 'BH1750', name='provider_vendor_enum'), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('unit', sa.Enum('WATT', 'KILOWATT', 'WATT_HOUR', 'KILOWATT_HOUR', 'VOLT', 'AMPERE', 'HERTZ', 'CELSIUS', 'FAHRENHEIT', 'KELVIN', 'PERCENT', 'LUX', 'BOOLEAN', 'STATE', 'NONE', name='power_unit_enum'), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('last_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('last_measurement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('polling_interval_sec', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['microcontroller_id'], ['microcontrollers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_microcontroller_id'), 'providers', ['microcontroller_id'], unique=False)
    op.create_index(op.f('ix_providers_uuid'), 'providers', ['uuid'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('microcontroller_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('device_number', sa.Integer(), nullable=False),
    sa.Column('rated_power_w', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('mode', sa.Enum('MANUAL', 'AUTO_POWER', 'SCHEDULE', name='device_mode_enum'), nullable=False),
    sa.Column('manual_state', sa.Boolean(), nullable=True),
    sa.Column('last_state_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['microcontroller_id'], ['microcontrollers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_microcontroller_id'), 'devices', ['microcontroller_id'], unique=False)
    op.create_index(op.f('ix_devices_provider_id'), 'devices', ['provider_id'], unique=False)
    op.create_index(op.f('ix_devices_uuid'), 'devices', ['uuid'], unique=True)
    op.create_table('provider_power_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('current_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_power_records_id'), 'provider_power_records', ['id'], unique=False)
    op.create_table('device_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('STATE', 'MODE', 'HEARTBEAT', 'AUTO_TRIGGER', 'SCHEDULER', 'ERROR', name='device_event_type_enum'), nullable=False),
    sa.Column('event_name', sa.Enum('DEVICE_ON', 'DEVICE_OFF', 'MANUAL_MODE_ON', 'AUTO_MODE_ON', 'AUTO_TRIGGER_ON', 'AUTO_TRIGGER_OFF', 'AUTO_SKIPPED_NO_SCHEDULE', 'AUTO_SKIPPED_DISABLED', 'HEARTBEAT_OK', 'HEARTBEAT_FAILED', 'PROVIDER_ERROR', 'DEVICE_ERROR', name='device_event_name_enum'), nullable=False),
    sa.Column('device_state', sa.String(), nullable=True, comment='Stan logiczny (np. ON/OFF)'),
    sa.Column('pin_state', sa.Boolean(), nullable=True, comment='Fizyczny stan GPIO / przekaźnika'),
    sa.Column('measured_value', sa.Numeric(precision=12, scale=4), nullable=True, comment='Wartość z providera (np. moc, temp)'),
    sa.Column('measured_unit', sa.String(length=16), nullable=True, comment='Jednostka (W, kW, C, %)'),
    sa.Column('trigger_reason', sa.String(), nullable=True, comment='Dlaczego zdarzenie wystąpiło'),
    sa.Column('source', sa.String(), nullable=True, comment='controller / agent / api'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_events_created_at'), 'device_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_events_device_id'), 'device_events', ['device_id'], unique=False)
    op.create_table('device_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='0=Mon, 6=Sun'),
    sa.Column('start_time', sa.String(), nullable=False, comment='HH:MM'),
    sa.Column('end_time', sa.String(), nullable=False, comment='HH:MM'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_schedules_device_id'), 'device_schedules', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_schedules_device_id'), table_name='device_schedules')
    op.drop_table('device_schedules')
    op.drop_index(op.f('ix_device_events_device_id'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_created_at'), table_name='device_events')
    op.drop_table('device_events')
    op.drop_index(op.f('ix_provider_power_records_id'), table_name='provider_power_records')
    op.drop_table('provider_power_records')
    op.drop_index(op.f('ix_devices_uuid'), table_name='devices')
    op.drop_index(op.f('ix_devices_provider_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_microcontroller_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_providers_uuid'), table_name='providers')
    op.drop_index(op.f('ix_providers_microcontroller_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_microcontrollers_uuid'), table_name='microcontrollers')
    op.drop_index(op.f('ix_microcontrollers_installation_id'), table_name='microcontrollers')
    op.drop_table('microcontrollers')
    op.drop_index(op.f('ix_installations_user_id'), table_name='installations')
    op.drop_index(op.f('ix_installations_station_code'), table_name='installations')
    op.drop_index(op.f('ix_installations_id'), table_name='installations')
    op.drop_table('installations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
