"""auto migration 2026-02-27T15:51:40.507092+00:00

Revision ID: 8fbd96e3c3cb
Revises: 65b41d7438f7
Create Date: 2026-02-27 16:51:45.213659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbd96e3c3cb'
down_revision: Union[str, Sequence[str], None] = '65b41d7438f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedulers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedulers_user_id'), 'schedulers', ['user_id'], unique=False)
    op.create_index(op.f('ix_schedulers_uuid'), 'schedulers', ['uuid'], unique=True)
    op.create_table('scheduler_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='scheduler_day_of_week_enum'), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False, comment='HH:MM'),
    sa.Column('end_time', sa.String(length=5), nullable=False, comment='HH:MM'),
    sa.ForeignKeyConstraint(['scheduler_id'], ['schedulers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_slots_scheduler_id'), 'scheduler_slots', ['scheduler_id'], unique=False)
    op.add_column('devices', sa.Column('scheduler_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_devices_scheduler_id'), 'devices', ['scheduler_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'schedulers', ['scheduler_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_scheduler_id'), table_name='devices')
    op.drop_column('devices', 'scheduler_id')
    op.drop_index(op.f('ix_scheduler_slots_scheduler_id'), table_name='scheduler_slots')
    op.drop_table('scheduler_slots')
    op.drop_index(op.f('ix_schedulers_uuid'), table_name='schedulers')
    op.drop_index(op.f('ix_schedulers_user_id'), table_name='schedulers')
    op.drop_table('schedulers')
    # ### end Alembic commands ###
