"""auto migration 2026-01-31T09:57:09.594885+00:00

Revision ID: 9e75726689cb
Revises: 633c213f079c
Create Date: 2026-01-31 10:57:09.864361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e75726689cb'
down_revision: Union[str, Sequence[str], None] = '633c213f079c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_provider_id'), table_name='devices')
    op.drop_constraint(op.f('devices_provider_id_fkey'), 'devices', type_='foreignkey')
    op.drop_column('devices', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('devices_provider_id_fkey'), 'devices', 'providers', ['provider_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_devices_provider_id'), 'devices', ['provider_id'], unique=False)
    # ### end Alembic commands ###
