"""auto migration 2025-12-13T18:58:20+00:00

Revision ID: 9f3cc8304eff
Revises: 
Create Date: 2025-12-13 19:58:20.314603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3cc8304eff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'NEW', 'CLIENT', 'CLIENT_PRO', 'DEMO', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('station_code', sa.String(length=255), nullable=False),
    sa.Column('station_addr', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_code')
    )
    op.create_index(op.f('ix_installations_id'), 'installations', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.Enum('API', 'SENSOR', 'VIRTUAL', name='provider_type_enum'), nullable=False),
    sa.Column('kind', sa.Enum('PV_INVERTER', name='provider_kind_enum'), nullable=False),
    sa.Column('vendor', sa.Enum('HUAWEI', 'GOODWE', 'SIEMENS', name='providervendor'), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('unit', sa.Enum('WATT', 'KILOWATT', 'LUX', 'CELSIUS', 'PERCENT', name='power_unit_enum'), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('last_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('last_measurement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('polling_interval_sec', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_installation_id'), 'providers', ['installation_id'], unique=False)
    op.create_index(op.f('ix_providers_uuid'), 'providers', ['uuid'], unique=True)
    op.create_table('provider_power_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('current_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_power_records_id'), 'provider_power_records', ['id'], unique=False)
    op.create_table('raspberries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('software_version', sa.String(), nullable=True),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raspberries_provider_id'), 'raspberries', ['provider_id'], unique=False)
    op.create_index(op.f('ix_raspberries_uuid'), 'raspberries', ['uuid'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raspberry_id', sa.Integer(), nullable=False),
    sa.Column('device_number', sa.Integer(), nullable=False),
    sa.Column('rated_power_kw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('mode', sa.Enum('MANUAL', 'AUTO_POWER', 'SCHEDULE', name='devicemode'), nullable=False),
    sa.Column('threshold_kw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('hysteresis_w', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manual_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['raspberry_id'], ['raspberries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_uuid'), 'devices', ['uuid'], unique=True)
    op.create_table('device_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pin_state', sa.Boolean(), nullable=False),
    sa.Column('trigger_reason', sa.String(), nullable=True),
    sa.Column('power_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('mode', sa.Enum('MANUAL', 'AUTO_POWER', 'SCHEDULE', name='device_mode'), nullable=False),
    sa.Column('threshold_kw', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_schedules')
    op.drop_table('device_events')
    op.drop_index(op.f('ix_devices_uuid'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_raspberries_uuid'), table_name='raspberries')
    op.drop_index(op.f('ix_raspberries_provider_id'), table_name='raspberries')
    op.drop_table('raspberries')
    op.drop_index(op.f('ix_provider_power_records_id'), table_name='provider_power_records')
    op.drop_table('provider_power_records')
    op.drop_index(op.f('ix_providers_uuid'), table_name='providers')
    op.drop_index(op.f('ix_providers_installation_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_installations_id'), table_name='installations')
    op.drop_table('installations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
