"""auto migration 2026-01-17T15:15:31.110742+00:00

Revision ID: e599cbe80578
Revises: c3f1b291c123
Create Date: 2026-01-17 16:15:31.360391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e599cbe80578'
down_revision: Union[str, Sequence[str], None] = 'c3f1b291c123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_measurements', 'measured_value',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('providers', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last measurement/heartbeat',
               existing_nullable=True)
    op.drop_column('providers', 'last_measurement_at')
    op.drop_column('providers', 'last_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('last_value', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('providers', sa.Column('last_measurement_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('providers', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last measurement/heartbeat',
               existing_nullable=True)
    op.alter_column('provider_measurements', 'measured_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
