"""auto migration 2025-12-25T12:48:36.477328+00:00

Revision ID: f920f5ff118b
Revises: ea1b4d6a9c9f
Create Date: 2025-12-25 13:48:36.752969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f920f5ff118b'
down_revision: Union[str, Sequence[str], None] = 'ea1b4d6a9c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('microcontrollers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_microcontrollers_power_provider_id', 'microcontrollers', 'providers', ['power_provider_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_microcontrollers_power_provider_id', 'microcontrollers', type_='foreignkey')
    op.alter_column('microcontrollers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
