from typing import List

from pydantic import ConfigDict, Field

from smart_common.enums.device_event import DeviceEventType
from smart_common.schemas.base import APIModel
from smart_common.schemas.device_event_schema import DeviceEventOut


class DeviceEventTimelineResponse(APIModel):
    events: List[DeviceEventOut] = Field(
        ...,
        description="Time-ordered events generated by the device",
    )
    total_minutes_on: int = Field(
        ...,
        description="Minutes the device recorded as ON",
        example=120,
    )
    energy_kwh: float | None = Field(
        None,
        description="Estimated energy consumption in kWh",
        example=1.2,
    )
    rated_power_kw: float | None = Field(
        None,
        description="Rated power for the device",
        example=1.5,
    )

    model_config = ConfigDict(
        from_attributes=True,
        extra="forbid",
        json_schema_extra={
            "example": {
                "events": [
                    {
                        "id": 1,
                        "device_id": 101,
                        "event_type": DeviceEventType.STATE,
                        "event_name": "DEVICE_ON",
                        "device_state": "ON",
                        "pin_state": True,
                        "measured_value": 1.25,
                        "measured_unit": "kW",
                        "trigger_reason": "AUTO_TRIGGER",
                        "source": "controller",
                        "created_at": "2024-01-02T12:00:00Z",
                    }
                ],
                "total_minutes_on": 60,
                "energy_kwh": 0.8,
                "rated_power_kw": 1.5,
            }
        },
    )
